kind: pipeline
type: docker
name: build-and-deploy

# Enable cancellation support
concurrency:
  limit: 1

steps:
  - name: detect-changed-services
    image: alpine/git:latest
    commands:
      - apk add --no-cache bash
      - |
        echo "ðŸ” Detecting changed services..."
        CHANGED_SERVICES=""
        
        # Get list of changed files compared to previous commit
        if [ "$DRONE_COMMIT_BEFORE" != "0000000000000000000000000000000000000000" ]; then
          CHANGED_FILES=$(git diff --name-only $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER || git diff --name-only HEAD~1 HEAD)
        else
          # First commit or no previous commit, check all files
          CHANGED_FILES=$(git ls-files)
        fi
        
        # Detect which services changed
        echo "$CHANGED_FILES" | grep -q "^User/" && CHANGED_SERVICES="$CHANGED_SERVICES user-service" || true
        echo "$CHANGED_FILES" | grep -q "^Ticket/" && CHANGED_SERVICES="$CHANGED_SERVICES ticket-service" || true
        echo "$CHANGED_FILES" | grep -q "^Subscription/" && CHANGED_SERVICES="$CHANGED_SERVICES subscription-service" || true
        echo "$CHANGED_FILES" | grep -q "^Route/" && CHANGED_SERVICES="$CHANGED_SERVICES route-service" || true
        echo "$CHANGED_FILES" | grep -q "^BusGeolocation/" && CHANGED_SERVICES="$CHANGED_SERVICES bus-geolocation-service" || true
        echo "$CHANGED_FILES" | grep -q "^Notification/" && CHANGED_SERVICES="$CHANGED_SERVICES notification-service" || true
        echo "$CHANGED_FILES" | grep -q "^api-gateway/" && CHANGED_SERVICES="$CHANGED_SERVICES api-gateway" || true
        echo "$CHANGED_FILES" | grep -q "^Frontend/" && CHANGED_SERVICES="$CHANGED_SERVICES frontend" || true
        echo "$CHANGED_FILES" | grep -q "^pom.xml\|^\.drone.yml\|^docker-compose" && CHANGED_SERVICES="all" || true
        
        # If no specific services changed but root files changed, rebuild all
        if [ -z "$CHANGED_SERVICES" ]; then
          CHANGED_SERVICES="all"
        fi
        
        # Trim whitespace
        CHANGED_SERVICES=$(echo $CHANGED_SERVICES | xargs)
        
        echo "ðŸ“¦ Changed services: $CHANGED_SERVICES"
        echo "CHANGED_SERVICES=$CHANGED_SERVICES" > /drone/src/changed_services.txt
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-user-service
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "user-service"; then
          echo "ðŸ”¨ Building User service..."
          mvn clean package -DskipTests -pl User -am
          echo "âœ… User service build completed"
        else
          echo "â­ï¸  User service unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-ticket-service
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "ticket-service"; then
          echo "ðŸ”¨ Building Ticket service..."
          mvn clean package -DskipTests -pl Ticket -am
          echo "âœ… Ticket service build completed"
        else
          echo "â­ï¸  Ticket service unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-subscription-service
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "subscription-service"; then
          echo "ðŸ”¨ Building Subscription service..."
          mvn clean package -DskipTests -pl Subscription -am
          echo "âœ… Subscription service build completed"
        else
          echo "â­ï¸  Subscription service unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-route-service
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "route-service"; then
          echo "ðŸ”¨ Building Route service..."
          mvn clean package -DskipTests -pl Route -am
          echo "âœ… Route service build completed"
        else
          echo "â­ï¸  Route service unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-bus-geolocation-service
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "bus-geolocation-service"; then
          echo "ðŸ”¨ Building BusGeolocation service..."
          mvn clean package -DskipTests -pl BusGeolocation -am
          echo "âœ… BusGeolocation service build completed"
        else
          echo "â­ï¸  BusGeolocation service unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-notification-service
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "notification-service"; then
          echo "ðŸ”¨ Building Notification service..."
          mvn clean package -DskipTests -pl Notification -am
          echo "âœ… Notification service build completed"
          ls -la Notification/target/*.jar || echo "âš ï¸  Notification JAR not found!"
        else
          echo "â­ï¸  Notification service unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: build-api-gateway
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        CHANGED_SERVICES=$(cat /drone/src/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        if [ "$CHANGED_SERVICES" = "all" ] || echo "$CHANGED_SERVICES" | grep -q "api-gateway"; then
          echo "ðŸ”¨ Building API Gateway..."
          mvn clean package -DskipTests -pl api-gateway -am
          echo "âœ… API Gateway build completed"
        else
          echo "â­ï¸  API Gateway unchanged, skipping build"
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request
        - custom

  - name: deploy-to-vps
    image: alpine/git:latest
    environment:
      VPS_HOST:
        from_secret: vps_host
      VPS_USER:
        from_secret: vps_user
      VPS_SSH_KEY:
        from_secret: vps_ssh_key
      DOCKER_USERNAME:
        from_secret: ghcr_username
      DOCKER_PASSWORD:
        from_secret: ghcr_token
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$$VPS_SSH_KEY" > ~/.ssh/deploy_key
      - chmod 600 ~/.ssh/deploy_key
      - ssh-keyscan -H $$VPS_HOST >> ~/.ssh/known_hosts || true
      - echo "ðŸ“¦ Copying source code to VPS..."
      - echo "VPS_HOST=$$VPS_HOST, VPS_USER=$$VPS_USER"
      - |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          $${DRONE_WORKSPACE}/ \
          "$$VPS_USER@$$VPS_HOST:/opt/soa-bus-app/"
      - echo "âœ… Deployment step (temporarily disabled for testing)"
    depends_on:
      - detect-changed-services
      - build-user-service
      - build-ticket-service
      - build-subscription-service
      - build-route-service
      - build-bus-geolocation-service
      - build-notification-service
      - build-api-gateway
    when:
      event:
        - push
        - custom
      branch:
        - master

volumes:
  - name: maven-cache
    temp: {}

