kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: detect-changed-services
    image: alpine/git:latest
    commands:
      - apk add --no-cache bash
      - |
        echo "🔍 Detecting changed services..."
        CHANGED_SERVICES=""
        
        # Get list of changed files compared to previous commit
        if [ "$DRONE_COMMIT_BEFORE" != "0000000000000000000000000000000000000000" ]; then
          CHANGED_FILES=$(git diff --name-only $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER || git diff --name-only HEAD~1 HEAD)
        else
          # First commit or no previous commit, check all files
          CHANGED_FILES=$(git ls-files)
        fi
        
        # Detect which services changed
        echo "$CHANGED_FILES" | grep -q "^User/" && CHANGED_SERVICES="$CHANGED_SERVICES user-service" || true
        echo "$CHANGED_FILES" | grep -q "^Ticket/" && CHANGED_SERVICES="$CHANGED_SERVICES ticket-service" || true
        echo "$CHANGED_FILES" | grep -q "^Subscription/" && CHANGED_SERVICES="$CHANGED_SERVICES subscription-service" || true
        echo "$CHANGED_FILES" | grep -q "^Route/" && CHANGED_SERVICES="$CHANGED_SERVICES route-service" || true
        echo "$CHANGED_FILES" | grep -q "^BusGeolocation/" && CHANGED_SERVICES="$CHANGED_SERVICES bus-geolocation-service" || true
        echo "$CHANGED_FILES" | grep -q "^api-gateway/" && CHANGED_SERVICES="$CHANGED_SERVICES api-gateway" || true
        echo "$CHANGED_FILES" | grep -q "^Frontend/" && CHANGED_SERVICES="$CHANGED_SERVICES frontend" || true
        echo "$CHANGED_FILES" | grep -q "^pom.xml\|^\.drone.yml\|^docker-compose" && CHANGED_SERVICES="all" || true
        
        # If no specific services changed but root files changed, rebuild all
        if [ -z "$CHANGED_SERVICES" ]; then
          CHANGED_SERVICES="all"
        fi
        
        # Trim whitespace
        CHANGED_SERVICES=$(echo $CHANGED_SERVICES | xargs)
        
        echo "📦 Changed services: $CHANGED_SERVICES"
        echo "CHANGED_SERVICES=$CHANGED_SERVICES" > /tmp/changed_services.txt
    when:
      event:
        - push
        - pull_request

  - name: build-backend-services
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - |
        echo "🔨 Building microservices..."
        
        # Read changed services
        CHANGED_SERVICES=$(cat /tmp/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        
        if [ "$CHANGED_SERVICES" = "all" ]; then
          echo "📦 Building all services (root files changed or first build)..."
          mvn clean package -DskipTests
        else
          echo "📦 Building only changed services: $CHANGED_SERVICES"
          
          # Build specific modules based on what changed
          MAVEN_MODULES=""
          echo "$CHANGED_SERVICES" | grep -q "user-service" && MAVEN_MODULES="$MAVEN_MODULES User" || true
          echo "$CHANGED_SERVICES" | grep -q "ticket-service" && MAVEN_MODULES="$MAVEN_MODULES Ticket" || true
          echo "$CHANGED_SERVICES" | grep -q "subscription-service" && MAVEN_MODULES="$MAVEN_MODULES Subscription" || true
          echo "$CHANGED_SERVICES" | grep -q "route-service" && MAVEN_MODULES="$MAVEN_MODULES Route" || true
          echo "$CHANGED_SERVICES" | grep -q "bus-geolocation-service" && MAVEN_MODULES="$MAVEN_MODULES BusGeolocation" || true
          echo "$CHANGED_SERVICES" | grep -q "api-gateway" && MAVEN_MODULES="$MAVEN_MODULES api-gateway" || true
          
          if [ -n "$MAVEN_MODULES" ]; then
            # Build only changed modules and their dependencies
            mvn clean package -DskipTests -pl $MAVEN_MODULES -am
          else
            echo "✅ No backend services changed, skipping Maven build"
          fi
        fi
    depends_on:
      - detect-changed-services
    when:
      event:
        - push
        - pull_request

  - name: deploy-to-vps
    image: alpine/git:latest
    environment:
      VPS_HOST:
        from_secret: vps_host
      VPS_USER:
        from_secret: vps_user
      VPS_SSH_KEY:
        from_secret: vps_ssh_key
      DOCKER_USERNAME:
        from_secret: ghcr_username
      DOCKER_PASSWORD:
        from_secret: ghcr_token
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$$VPS_SSH_KEY" > ~/.ssh/deploy_key
      - chmod 600 ~/.ssh/deploy_key
      - ssh-keyscan -H $$VPS_HOST >> ~/.ssh/known_hosts || true
      - echo "📦 Copying source code to VPS..."
      - echo "VPS_HOST=$$VPS_HOST, VPS_USER=$$VPS_USER"
      - |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          $${DRONE_WORKSPACE}/ \
          "$$VPS_USER@$$VPS_HOST:/opt/soa-bus-app/"
      - echo "🚀 Building and deploying services on VPS..."
      - |
        # Read changed services and pass to VPS
        CHANGED_SERVICES=$(cat /tmp/changed_services.txt 2>/dev/null | grep CHANGED_SERVICES= | cut -d'=' -f2 || echo "all")
        echo "📦 Changed services to build: $CHANGED_SERVICES"
        
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$$VPS_USER@$$VPS_HOST" << DEPLOYSCRIPT
          cd /opt/soa-bus-app
          set -a && source .env && set +a
          
          # Get commit SHA from environment or git
          COMMIT_SHA="${DRONE_COMMIT_SHA:0:8}"
          if [ -z "\$COMMIT_SHA" ] || [ "\$COMMIT_SHA" = "" ]; then
            COMMIT_SHA=\$(git rev-parse --short=8 HEAD 2>/dev/null || echo "latest")
          fi
          
          # Detect changed services on VPS using git
          CHANGED_SERVICES_VPS="all"
          if [ -d .git ]; then
            PREV_COMMIT=\$(git rev-parse HEAD~1 2>/dev/null || echo "")
            if [ -n "\$PREV_COMMIT" ]; then
              CHANGED_FILES=\$(git diff --name-only \$PREV_COMMIT HEAD 2>/dev/null || echo "")
              if [ -n "\$CHANGED_FILES" ]; then
                CHANGED_SERVICES_VPS=""
                echo "\$CHANGED_FILES" | grep -q "^User/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS user-service" || true
                echo "\$CHANGED_FILES" | grep -q "^Ticket/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS ticket-service" || true
                echo "\$CHANGED_FILES" | grep -q "^Subscription/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS subscription-service" || true
                echo "\$CHANGED_FILES" | grep -q "^Route/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS route-service" || true
                echo "\$CHANGED_FILES" | grep -q "^BusGeolocation/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS bus-geolocation-service" || true
                echo "\$CHANGED_FILES" | grep -q "^api-gateway/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS api-gateway" || true
                echo "\$CHANGED_FILES" | grep -q "^Frontend/" && CHANGED_SERVICES_VPS="\$CHANGED_SERVICES_VPS frontend" || true
                echo "\$CHANGED_FILES" | grep -q "^pom.xml\|^\.drone.yml\|^docker-compose" && CHANGED_SERVICES_VPS="all" || true
                CHANGED_SERVICES_VPS=\$(echo \$CHANGED_SERVICES_VPS | xargs)
                [ -z "\$CHANGED_SERVICES_VPS" ] && CHANGED_SERVICES_VPS="all" || true
              fi
            fi
          fi
          
          echo "🔐 Logging in to GHCR..."
          echo "${DOCKER_PASSWORD}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
          
          echo "📝 Using commit SHA: \$COMMIT_SHA"
          
          # Function to build and push a service
          build_and_push() {
            local SERVICE_NAME=\$1
            local DOCKERFILE=\$2
            local IMAGE_NAME=\$3
            local BUILD_ARGS=\$4
            
            echo "🔨 Building \$SERVICE_NAME..."
            if [ -n "\$BUILD_ARGS" ]; then
              docker build \$BUILD_ARGS -t ghcr.io/ettomarett/\$IMAGE_NAME:\${COMMIT_SHA} -t ghcr.io/ettomarett/\$IMAGE_NAME:latest -f \$DOCKERFILE .
            else
              docker build -t ghcr.io/ettomarett/\$IMAGE_NAME:\${COMMIT_SHA} -t ghcr.io/ettomarett/\$IMAGE_NAME:latest -f \$DOCKERFILE .
            fi
            
            echo "📤 Pushing \$SERVICE_NAME..."
            docker push ghcr.io/ettomarett/\$IMAGE_NAME:\${COMMIT_SHA}
            docker push ghcr.io/ettomarett/\$IMAGE_NAME:latest
          }
          
          if [ "\$CHANGED_SERVICES_VPS" = "all" ]; then
            echo "🔨 Building all services..."
            build_and_push "user-service" "User/Dockerfile" "soa-bus-app-user-service"
            build_and_push "ticket-service" "Ticket/Dockerfile" "soa-bus-app-ticket-service"
            build_and_push "subscription-service" "Subscription/Dockerfile" "soa-bus-app-subscription-service"
            build_and_push "route-service" "Route/Dockerfile" "soa-bus-app-route-service"
            build_and_push "bus-geolocation-service" "BusGeolocation/Dockerfile" "soa-bus-app-bus-geolocation-service"
            build_and_push "api-gateway" "api-gateway/Dockerfile" "soa-bus-app-api-gateway"
            build_and_push "frontend" "Frontend/Dockerfile" "soa-bus-app-frontend" "--build-arg REACT_APP_API_URL=https://nassar.clueleak.com/api/v1 --build-arg REACT_APP_USER_SERVICE_URL=https://nassar.clueleak.com/api/v1"
          else
            echo "🔨 Building only changed services: \$CHANGED_SERVICES_VPS"
            echo "\$CHANGED_SERVICES_VPS" | grep -q "user-service" && build_and_push "user-service" "User/Dockerfile" "soa-bus-app-user-service" || true
            echo "\$CHANGED_SERVICES_VPS" | grep -q "ticket-service" && build_and_push "ticket-service" "Ticket/Dockerfile" "soa-bus-app-ticket-service" || true
            echo "\$CHANGED_SERVICES_VPS" | grep -q "subscription-service" && build_and_push "subscription-service" "Subscription/Dockerfile" "soa-bus-app-subscription-service" || true
            echo "\$CHANGED_SERVICES_VPS" | grep -q "route-service" && build_and_push "route-service" "Route/Dockerfile" "soa-bus-app-route-service" || true
            echo "\$CHANGED_SERVICES_VPS" | grep -q "bus-geolocation-service" && build_and_push "bus-geolocation-service" "BusGeolocation/Dockerfile" "soa-bus-app-bus-geolocation-service" || true
            echo "\$CHANGED_SERVICES_VPS" | grep -q "api-gateway" && build_and_push "api-gateway" "api-gateway/Dockerfile" "soa-bus-app-api-gateway" || true
            echo "\$CHANGED_SERVICES_VPS" | grep -q "frontend" && build_and_push "frontend" "Frontend/Dockerfile" "soa-bus-app-frontend" "--build-arg REACT_APP_API_URL=https://nassar.clueleak.com/api/v1 --build-arg REACT_APP_USER_SERVICE_URL=https://nassar.clueleak.com/api/v1" || true
          fi
          
          # Use docker-compose.production.yml if it exists, otherwise use docker-compose.yml
          if [ -f docker-compose.production.yml ]; then
            COMPOSE_FILE="docker-compose.production.yml"
          elif [ -f docker-compose.yml ]; then
            COMPOSE_FILE="docker-compose.yml"
            echo "⚠️  Using docker-compose.yml (production file not found)"
          else
            echo "❌ No docker-compose file found!"
            exit 1
          fi
          
          echo "🚀 Starting services with \$COMPOSE_FILE..."
          docker compose -f \$COMPOSE_FILE up -d
          echo "✅ Deployment complete!"
          docker compose -f \$COMPOSE_FILE ps
        DEPLOYSCRIPT
    depends_on:
      - detect-changed-services
      - build-backend-services
    when:
      event:
        - push
      branch:
        - master

volumes:
  - name: maven-cache
    temp: {}

