kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: build-backend-services
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - echo "Building all microservices..."
      - mvn clean package -DskipTests
    when:
      event:
        - push
        - pull_request

  - name: deploy-to-vps
    image: alpine/git:latest
    environment:
      VPS_HOST:
        from_secret: vps_host
      VPS_USER:
        from_secret: vps_user
      VPS_SSH_KEY:
        from_secret: vps_ssh_key
      DOCKER_USERNAME:
        from_secret: ghcr_username
      DOCKER_PASSWORD:
        from_secret: ghcr_token
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$$VPS_SSH_KEY" > ~/.ssh/deploy_key
      - chmod 600 ~/.ssh/deploy_key
      - ssh-keyscan -H $$VPS_HOST >> ~/.ssh/known_hosts || true
      - echo "ðŸ“¦ Copying source code to VPS..."
      - echo "VPS_HOST=$$VPS_HOST, VPS_USER=$$VPS_USER"
      - |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          $${DRONE_WORKSPACE}/ \
          "$$VPS_USER@$$VPS_HOST:/opt/soa-bus-app/"
      - echo "ðŸš€ Building and deploying services on VPS..."
      - |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$$VPS_USER@$$VPS_HOST" << EOF
          cd /opt/soa-bus-app
          set -a && source .env && set +a
          echo "ðŸ” Logging in to GHCR..."
          echo "${DOCKER_PASSWORD}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
          echo "ðŸ”¨ Building Docker images on VPS..."
          COMMIT_SHA="${DRONE_COMMIT_SHA:0:8}"
          docker build -t ghcr.io/ettomarett/soa-bus-app-user-service:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-user-service:latest -f User/Dockerfile .
          docker build -t ghcr.io/ettomarett/soa-bus-app-ticket-service:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-ticket-service:latest -f Ticket/Dockerfile .
          docker build -t ghcr.io/ettomarett/soa-bus-app-subscription-service:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-subscription-service:latest -f Subscription/Dockerfile .
          docker build -t ghcr.io/ettomarett/soa-bus-app-route-service:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-route-service:latest -f Route/Dockerfile .
          docker build -t ghcr.io/ettomarett/soa-bus-app-bus-geolocation-service:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-bus-geolocation-service:latest -f BusGeolocation/Dockerfile .
          docker build -t ghcr.io/ettomarett/soa-bus-app-api-gateway:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-api-gateway:latest -f api-gateway/Dockerfile .
          docker build --build-arg REACT_APP_API_URL=https://nassar.clueleak.com/api/v1 --build-arg REACT_APP_USER_SERVICE_URL=https://nassar.clueleak.com/api/v1 -t ghcr.io/ettomarett/soa-bus-app-frontend:\${COMMIT_SHA} -t ghcr.io/ettomarett/soa-bus-app-frontend:latest -f Frontend/Dockerfile .
          echo "ðŸ“¤ Pushing images to GHCR..."
          docker push ghcr.io/ettomarett/soa-bus-app-user-service:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-user-service:latest
          docker push ghcr.io/ettomarett/soa-bus-app-ticket-service:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-ticket-service:latest
          docker push ghcr.io/ettomarett/soa-bus-app-subscription-service:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-subscription-service:latest
          docker push ghcr.io/ettomarett/soa-bus-app-route-service:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-route-service:latest
          docker push ghcr.io/ettomarett/soa-bus-app-bus-geolocation-service:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-bus-geolocation-service:latest
          docker push ghcr.io/ettomarett/soa-bus-app-api-gateway:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-api-gateway:latest
          docker push ghcr.io/ettomarett/soa-bus-app-frontend:\${COMMIT_SHA}
          docker push ghcr.io/ettomarett/soa-bus-app-frontend:latest
          echo "ðŸš€ Starting services..."
          docker compose -f docker-compose.production.yml up -d
          echo "âœ… Deployment complete!"
          docker compose -f docker-compose.production.yml ps
        EOF
    depends_on:
      - build-backend-services
    when:
      event:
        - push
      branch:
        - master

volumes:
  - name: maven-cache
    temp: {}

